var quest=me.ObjectEntity.extend({init:function(a,c,d){this.id=d.id;this.parent(a,c,d);this.name="quest";this.selected=!1;this.gravity=0;this.addAnimation("closed",[0]);this.addAnimation("open",[9]);this.setCurrentAnimation("closed");this.collidable=!0},update:function(){return!0}}),Players=me.ObjectEntity.extend({init:function(a,c,d){d.spritewidth=32;d.spriteheight=32;this.parent(a,c,d);this.setVelocity(2,2);this.setFriction(0.2,0.2);this.gravity=0;this.direction="down";this.destinationX=a;this.destinationY=
c;this.updateColRect(2,26,-1,0);this.addAnimation("down",[0,1,2]);this.addAnimation("left",[3,4,5]);this.addAnimation("up",[9,10,11]);this.addAnimation("right",[6,7,8]);this.addAnimation("stand-down",[0]);this.addAnimation("stand-left",[3]);this.addAnimation("stand-up",[9]);this.addAnimation("stand-right",[6])},update:function(){hadSpeed=0!==this.vel.y||0!==this.vel.x;this.handleInput();updated=this.updateMovement();0===this.vel.x&&0===this.vel.y&&(this.setCurrentAnimation("stand-"+this.direction),
hadSpeed&&(updated=!0));updated&&this.parent(this);return updated},handleInput:function(){this.destinationX<this.pos.x-10?(this.vel.x-=this.accel.x*me.timer.tick,this.setCurrentAnimation("left"),this.direction="left"):this.destinationX>this.pos.x+10&&(this.vel.x+=this.accel.x*me.timer.tick,this.setCurrentAnimation("right"),this.direction="right");this.destinationY<this.pos.y-10?(this.vel.y=-this.accel.y*me.timer.tick,this.setCurrentAnimation("up"),this.direction="up"):this.destinationY>this.pos.y+
10&&(this.vel.y=this.accel.y*me.timer.tick,this.setCurrentAnimation("down"),this.direction="down")}}),LocalPlayer=Players.extend({init:function(a,c,d){d.image=now.player.spr;a=now.player.x;c=now.player.y;this.parent(a,c,d);this.setVelocity(1,1);this.setFriction(0.2,0.2);this.gravity=0;this.collidable=!0;this.type="player";me.game.viewport.follow(this.pos,me.game.viewport.AXIS.BOTH)},update:function(){var a=this.pos.x,c=this.pos.y;hadSpeed=0!==this.vel.y||0!==this.vel.x;this.handleInput();updated=
this.updateMovement();0===this.vel.x&&0===this.vel.y&&(this.setCurrentAnimation("stand-"+this.direction),hadSpeed&&(updated=!0));for(b in mobs){if("undefined"==typeof b)return;if(150>this.distanceTo(mobs[b])){var d=100*mobs[b].hp/mobs[b].maxhp;"undefined"!=typeof $("#target_"+b)[0]?$("#target_hp_"+b).css("width",d+"%"):($("#combat_list").append("<div class='target_name' id='target_"+b+"' style='text-align:left;'>"+mobs[b].name+"</div>"),$("#combat_list").append("<div class='target_hp_cont' id='hp_"+
b+"'><div id='target_hp_"+b+"' class='target_hp' style='width:"+d+"%'></div></div>"))}else"undefined"!=typeof $("#target_"+b)[0]&&($("#target_"+b).remove(),$("#hp_"+b).remove())}if(res=me.game.collide(this)){if(res.name=me.input.isKeyPressed("action")&&!1==res.obj.selected){for(var b=1;16>=b&&0!=local_inventario[b].item;)b++;16>b?(res.obj.setCurrentAnimation("open"),res.obj.selected=!0,now.sendQuest({id:res.obj.id})):$("#c_msgs").append("You need a free slot in your inventory.<br/>")}res.type==me.game.ENEMY_OBJECT&&
me.input.isKeyPressed("action")?(d=res.obj.hp,now.attack(res.obj.id_,0),res.obj.hp!=d&&res.obj.flicker(10)):now.attack(res.obj.id_,1);0<res.y&&(this.pos.y=c-2);0>res.y&&(this.pos.y=c+2);0<res.x&&(this.pos.x=a-1);0>res.x&&(this.pos.x=a+1)}updated&&this.parent(this);return updated},handleInput:function(){me.input.isKeyPressed("left")?(this.vel.x-=this.accel.x*me.timer.tick,this.setCurrentAnimation("left"),this.direction="left"):me.input.isKeyPressed("right")&&(this.vel.x+=this.accel.x*me.timer.tick,
this.setCurrentAnimation("right"),this.direction="right");me.input.isKeyPressed("up")?(this.vel.y=-this.accel.y*me.timer.tick,this.setCurrentAnimation("up"),this.direction="up"):me.input.isKeyPressed("down")&&(this.vel.y=this.accel.y*me.timer.tick,this.setCurrentAnimation("down"),this.direction="down");if(0!=this.vel.x||0!=this.vel.y)now.moverPlayer({pos:{x:this.pos.x,y:this.pos.y}}),chatOn=!1}});
now.actualizarPlayers=function(a){if(init&&a.id!=now.player.id){me.ObjectSettings.name=a.nick;me.ObjectSettings.image=a.spr;players["'"+a.id+"'"]||(players["'"+a.id+"'"]=new Players(a.x,a.y,me.ObjectSettings),players["'"+a.id+"'"].z=7,me.game.add(players["'"+a.id+"'"]),me.game.sort());var c=players["'"+a.id+"'"];c.destinationX=a.x;c.destinationY=a.y}};now.recibeQuest=function(a){var c=0;$.each(now.player.inventario,function(a,b){0!=b.item&&c++});16>c?addItemInventory(a.item,a.cantidad):console.log("Sin capacidad")};
now.del_player=function(a){init&&me.game.remove(players["'"+a+"'"])};